### ISSUE TITLE
Logo For simple ToDo

### ISSUE THREAD

**Issue by somrat420** [Jizzu/SimpleToDo#11]
Hi @jizu , I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good but this app does not yet have a logo. Therefore I suggest a logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by Jizzu** [comment]
Hello,  @somrat420 . It's great idea! Please, contact me by Gmail: ilya.ponomarenko.dev@gmail.com to discuss all the details.

**Comment by somrat420** [comment]
Hi @jizzu this is the logo I have designed for your project, what do you think? Which one do you like? or if there is something part want to be changed please let me know
![todo1-01](https://user-images.githubusercontent.com/39495250/41885737-1507f1c8-791b-11e8-9c26-cc884247c382.jpg)

**Comment by somrat420** [comment]
Which number do you like? It's free.

**Comment by Jizzu** [comment]
Hello, @somrat420 ! Thanks for your work and sorry for delayed response. I appreciate your efforts, but no one of this icons is not suitable for my app. Anyway, I wish you succeed in your endeavors.
