### ISSUE TITLE
Proposal to prepare a privacy policy document for your project

### ISSUE THREAD

**Issue by Anyadan** [Jizzu/SimpleToDo#12]
Hello sir, I'll love to contribute to this project once again with a Privacy Policy document which I think will be useful.

The Privacy Policy document would contain details of how your app collects personal information if it does, and how this information is utilized.

A response from you would be very appreciated.

**Comment by Jizzu** [comment]
Hello, @Anyadan ! Thanks for your desire to help. But in my app there is no privacy policy, because it doesn't collect any personal data of users.
