### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by IzzySoft** [Jizzu/SimpleToDo#13]
It would be really nice to have your app available on F-Droid – ***THE*** place for free and open-source Android apps. I took the freedom to file a [request for packaging](https://gitlab.com/fdroid/rfp/issues/677) for you already. Would you support that?

**Comment by paulle** [comment]
It's on f-droid now.

**Comment by IzzySoft** [comment]
@paulle Yes (I requested it there). Would still be nice to have @Jizzu agree explicitly :wink:

**Comment by Jizzu** [comment]
Hi, @IzzySoft ! Ok, I agree with publication of my app on F-Droid. But I couldn't find it there using the search. Please, can you give me a link to the Simple ToDo page on F-Droid?

**Comment by IzzySoft** [comment]
@Jizzu Thanks! And sure: https://f-droid.org/packages/apps.jizzu.simpletodo/

**Comment by licaon-kter** [comment]
The inclusion of non-free Crashlytics will make this unbuildable on F-Droid

@Jizzu Could you implement a flavour without it?

**Comment by Jizzu** [comment]
@licaon-kter  Crashlytics is free:
![screenshot_2](https://user-images.githubusercontent.com/29975166/53645187-e6546000-3c6a-11e9-9905-2a3d9000a693.png)

**Comment by licaon-kter** [comment]
The libs are not open source.

Yes the service might be, but I can't build Crashlitycs, can I?
