### ISSUE TITLE
Don't mention store name

### ISSUE THREAD

**Issue by licaon-kter** [Jizzu/SimpleToDo#14]
Given that the app will be in F-Droid soon (#13) could you (or I) remove the [store name mention](https://github.com/Jizzu/SimpleToDo/blob/d182530b53e029596e0ddbc6093463760c28a6fa/app/src/main/res/values/strings.xml#L26)?

Yes it won't do anything on F-Droid [yet](https://gitlab.com/fdroid/fdroidclient/issues/646), but looks nicer. ;)

**Comment by licaon-kter** [comment]
So no?

**Comment by Jizzu** [comment]
@licaon-kter I see no problems in the fact that in the SimpleToDo there is a mention of Google Play store. Why I should remove it?

**Comment by licaon-kter** [comment]
Not sure what's the use of the button since it will just open F-Droid instead...

**Comment by Jizzu** [comment]
@licaon-kter Why the button should open F-Droid if it's sending the user to the app page on Google Play store?

**Comment by licaon-kter** [comment]
Because of `intents` like `market://` and F-Droid as a store associates it self, as expected....if it's the only store specially.
