### ISSUE TITLE
adding repeat function to reminder

### ISSUE THREAD

**Issue by paulle** [Jizzu/SimpleToDo#15]
First thank you for your great app.
May be you can add a repeating function to the reminder (daily, hourly, monthly and yearly). 
It would make the reminder more useful for different use cases.

**Comment by Jizzu** [comment]
Hello, @paulle ! Yes, I plan to add this feature in the future, because many users are asking about this.

**Comment by paulle** [comment]
Thank you.

**Comment by lionirdeadman** [comment]
Shouldn't be left open until it is done?  @Jizzu

**Comment by esmoak** [comment]
Would also like to see this feature.
