### ISSUE TITLE
[Feature Request] Remove the title in the widget 

### ISSUE THREAD

**Issue by ghost** [Jizzu/SimpleToDo#21]
I have found that the title in the widget unnecessarily takes up screen space. Could you remove it? The bottom of the title text is also slightly clipped off, so that is also a problem.

**Comment by Jizzu** [comment]
Hello, @starun96 ! Thanks for your feedback :)
This title on the widget has it's own specific function — by clicking on it, you can open the app. Therefore, I probably will not remove it. Also, can you send me a screenshot with clipped widget title? Cause I haven't seen any problem here...

**Comment by ghost** [comment]
Okay, well is it possible that the title could be smaller?

Here is the image: (I am using the Lawnchair launcher)

![screenshot_20190122-213607_lawnchair](https://user-images.githubusercontent.com/6378869/51579179-0172c980-1e8e-11e9-9598-c179be6beb5c.jpg)

**Comment by Jizzu** [comment]
Hi, @starun96 ! I probably fixed the problem with the clipped widget title. Wait for the app update :)

Now the widget looks something like this:

![screenshot_20190202-154237_evie](https://user-images.githubusercontent.com/29975166/52162146-12c79b80-2702-11e9-94a7-d634ff6a6afa.png)
