### ISSUE TITLE
App Crashes on Huawei after latest EMUI update

### ISSUE THREAD

**Issue by KGMIT** [Jizzu/SimpleToDo#22]
Device is Huawei CLT-L29 (P20 Pro) and the EMUI version is 9.0.0 (this is the update after which SimpleToDo stopped working I believe) and the android version is 9.

As the title says, after the latest update (which I believe was an EMUI update and not android itself, which I think also included some security patches from the December 1 Android security patch) the application cannot launch. I will click it and it will flash for a second as if the screen was going to change to the application, but then it immediately closes. Same happens when trying to enter the application from the widget's title button.

I'd be happy to give it a go in terms of debugging but any pointers as to how I could do that would be appreciated. (I'm assuming using Android Studio?)

**Comment by esmoak** [comment]
I have a Huawei on 8.0, and recently got an EMUI update, but I don't have this issue. 

Have you tried clearing app data and reinstalling?

**Comment by Jizzu** [comment]
Hello, @KGMIT ! Probably your problem is not in the new EMUI version, but in the critical bugs of the app itself. Try to clear the app data or reinstall it, as @esmoak advised.

Also wait for the next app update. It contains a lot of stability improvements :)
