### ISSUE TITLE
Tabula rasa or why all my tasks disappeared

### ISSUE THREAD

**Issue by OrangeFlag** [Jizzu/SimpleToDo#26]
I don't know why, but there were 3 cases of complete cleaning of my todo list. I haven't identified patterns.
But can you make auto backup and auto recovery in case of failures?

**Comment by Jizzu** [comment]
Hello, @OrangeFlag ! This critical bug was fixed in version 1.5. Now everything works fine :)

**Comment by OrangeFlag** [comment]
> Hello, @OrangeFlag ! This critical bug was fixed in version 1.5. Now everything works fine :)

Thank you! :+1:
