### ISSUE TITLE
Sorting after reminder?

### ISSUE THREAD

**Issue by tdoerrich** [Jizzu/SimpleToDo#27]
I was wondering if you could add a feature so I could sort after the task reminder. Eg. if I have 10 tasks today, one at 8 am, one a 9am, etc. That it would put the tasks in that order. 8 am at the top, then the 0 am etc. rather then the current one where it sorts after how I created them.

**Comment by Jizzu** [comment]
Hello, @TobiasDev ! Yes, I will try to implement this feature in the future app updates.
