### ISSUE TITLE
Adaptive icon support

### ISSUE THREAD

**Issue by lokesh-krishna** [Jizzu/SimpleToDo#3]
I can't thank you enough for creating something this solid and gorgeous!  

Could you please consider looking into adding support for adaptive icons?  

The relevant documentation can be found here: [Adaptive icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive).

**Comment by Jizzu** [comment]
@lokesh-krishna Hello. I'm will try to add adaptive icon in the future updates.

**Comment by lokesh-krishna** [comment]
Awesome! Looking forward to it!
