### ISSUE TITLE
Add Ability To Change and Set Notification Sound

### ISSUE THREAD

**Issue by jubreal** [Jizzu/SimpleToDo#32]
I want to suggest a feature that users should be able to Change and Set Notification Sound, (even though while going through the Project's FAQs, I found out this particular feature was said to be present in the app which sadly I've looked for tirelessly and still couldn't find it).
I don't know if it's present in the older versions, but it seems to be missing in the latest version.
This is what the notification options page currently looks like 
![Screenshot_20190523-174309](https://user-images.githubusercontent.com/37203158/58271149-48f95b80-7d83-11e9-9d00-f11cdacb1879.png)
Please look into it.
Thanks.

**Comment by Jizzu** [comment]
Hello, @jubreal . Yes, this feature works only on phones with Android 8.0 or higher.
