### ISSUE TITLE
App crashes while opening widgets 

### ISSUE THREAD

**Issue by kr-nahid** [Jizzu/SimpleToDo#9]
#### Expected behavior
user should be able to open **Simple To Do** widgets without crash .

#### Actual behavior
when click on **Simple To Do** widgets it crash and can't open widgets .

#### How to reproduce
* download the app
* open it and click on (+) button
* and create new task and save it
* then go to your phone widgets and find **Simple To Do** widgets then put it to your home screen .
* now click on your task in widgets and note the bug

> Browser/App version: Simple To Do v1.2
 Operating system: android 6.0

#### Recording Of The Bug
https://www.youtube.com/watch?v=NR2PlWxoom0

**Comment by Jizzu** [comment]
Fixed in version 1.6.5
